version: '3.8'

services:
  # 1. Our custom Go Application
  api:
    build: .
    container_name: uptime-api
    ports:
      - "8080:8080"
    environment:
      # Here we tell Go the EXACT names of the other containers!
      - REDIS_ADDR=redis:6379
      - POSTGRES_DSN=postgres://admin:password@postgres:5432/monitor_db?sslmode=disable
      - WORKER_COUNT=25
    depends_on:
      - redis
      - postgres
    restart: always

  # 2. Redis Buffer
  redis:
    image: redis:alpine
    container_name: uptime-redis
    ports:
      - "6379:6379"
    restart: always

  # 3. Permanent Storage
  postgres:
    image: postgres:15-alpine
    container_name: uptime-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: monitor_db
    ports:
      - "5432:5432"
    restart: always